#dataset: ml-100k
#field_separator: "\t"
#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: item_id
#RATING_FIELD: rating
#TIME_FIELD: timestamp
#
#load_col:
#    inter: [user_id, item_id, rating, timestamp]
#
#neg_sampling: ~
